/*****************************************************************************
 * dr.h
 * Copyright (C) 2001-2010 VideoLAN
 *
 * Authors: Arnaud de Bossoreille de Ribou <bozo@via.ecp.fr>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 *****************************************************************************/

/*!
 * \file <dr.h>
 * \author Arnaud de Bossoreille de Ribou <bozo@via.ecp.fr>
 * \brief Gather all dr_*.h into one.
 *
 * Gathers all dr_*.h into one. Use this header if you need a lot of them.
 */

/* This file is auto-generated by misc/gen_dr_h.sh. Please remember to update
 * it when adding directories to src/descriptors. */

#ifndef _DVBPSI_DR_H_
#define _DVBPSI_DR_H_
#include "dvbpsi/atsc/dr_81.h"
#include "dvbpsi/atsc/dr_86.h"
#include "dvbpsi/atsc/dr_a0.h"
#include "dvbpsi/atsc/dr_a1.h"
#include "dvbpsi/dvb/dr_40.h"
#include "dvbpsi/dvb/dr_41.h"
#include "dvbpsi/dvb/dr_42.h"
#include "dvbpsi/dvb/dr_43.h"
#include "dvbpsi/dvb/dr_44.h"
#include "dvbpsi/dvb/dr_45.h"
#include "dvbpsi/dvb/dr_47.h"
#include "dvbpsi/dvb/dr_48.h"
#include "dvbpsi/dvb/dr_49.h"
#include "dvbpsi/dvb/dr_4a.h"
#include "dvbpsi/dvb/dr_4b.h"
#include "dvbpsi/dvb/dr_4c.h"
#include "dvbpsi/dvb/dr_4d.h"
#include "dvbpsi/dvb/dr_4e.h"
#include "dvbpsi/dvb/dr_4f.h"
#include "dvbpsi/dvb/dr_50.h"
#include "dvbpsi/dvb/dr_52.h"
#include "dvbpsi/dvb/dr_53.h"
#include "dvbpsi/dvb/dr_54.h"
#include "dvbpsi/dvb/dr_55.h"
#include "dvbpsi/dvb/dr_56.h"
#include "dvbpsi/dvb/dr_58.h"
#include "dvbpsi/dvb/dr_59.h"
#include "dvbpsi/dvb/dr_5a.h"
#include "dvbpsi/dvb/dr_62.h"
#include "dvbpsi/dvb/dr_66.h"
#include "dvbpsi/dvb/dr_69.h"
#include "dvbpsi/dvb/dr_73.h"
#include "dvbpsi/dvb/dr_76.h"
#include "dvbpsi/dvb/dr_7c.h"
#include "dvbpsi/mpeg/dr_02.h"
#include "dvbpsi/mpeg/dr_03.h"
#include "dvbpsi/mpeg/dr_04.h"
#include "dvbpsi/mpeg/dr_05.h"
#include "dvbpsi/mpeg/dr_06.h"
#include "dvbpsi/mpeg/dr_07.h"
#include "dvbpsi/mpeg/dr_08.h"
#include "dvbpsi/mpeg/dr_09.h"
#include "dvbpsi/mpeg/dr_0a.h"
#include "dvbpsi/mpeg/dr_0b.h"
#include "dvbpsi/mpeg/dr_0c.h"
#include "dvbpsi/mpeg/dr_0d.h"
#include "dvbpsi/mpeg/dr_0e.h"
#include "dvbpsi/mpeg/dr_0f.h"
#include "dvbpsi/mpeg/dr_10.h"
#include "dvbpsi/mpeg/dr_11.h"
#include "dvbpsi/mpeg/dr_12.h"
#include "dvbpsi/mpeg/dr_13.h"
#include "dvbpsi/mpeg/dr_14.h"
#include "dvbpsi/mpeg/dr_1b.h"
#include "dvbpsi/mpeg/dr_1c.h"
#include "dvbpsi/mpeg/dr_24.h"
#include "dvbpsi/custom/dr_83_eacem.h"
#include "dvbpsi/custom/dr_8a_scte.h"
#include "dvbpsi/ssu/ssu_dr_01.h"
#include "dvbpsi/ssu/ssu_dr_02.h"
#include "dvbpsi/ssu/ssu_dr_03.h"
#include "dvbpsi/ssu/ssu_dr_04.h"
#include "dvbpsi/ssu/ssu_dr_06.h"
#include "dvbpsi/ssu/ssu_dr_07.h"
#include "dvbpsi/ssu/ssu_dr_08.h"
#include "dvbpsi/ssu/ssu_dr_09.h"
#include "dvbpsi/ssu/ssu_dr_0a.h"
#include "dvbpsi/ssu/ssu_dr_0b.h"

#endif
